<?php
/** @var Magento\Backend\Block\Template $block */
?>
<script type="text/javascript">
    require(['jquery', 'Magento_Theme/js/sortable'], function ($) {
        var searchValue = null, typeFilterValue = null;

        $(window).load(function () {
            $(".devdashboard_developer_widgets").sortable({
                placeholder: "devdashboard_developer_widgets_placeholder",
                forcePlaceholderSize: true,
                handle: "h3",
                connectWith: ".devdashboard_developer_widgets"
            });
            $(".devdashboard_developer_widgets h2").addClass('devdashboard_developer_widgets_handle');
        });
    });
</script>
