<?php
/** @var \Magento\Backend\Block\Template $block */
?>
<div class="shadow rounded border-b border-gray-200 mb-8 bg-white">
    <h3 class="cursor-move
        px-6 py-10 border-b border-green-200 bg-green-50
        text-left text-lg leading-4 font-medium text-green-500 tracking-wider"
    ><?= $block->escapeHtml(__($block->getData('title'))) ?></h3>
    <div class="p-5"><?= $block->getChildHtml(); ?></div>
</div>
