<?php
/** @var Magento\Backend\Block\Template $block */
/** @var \Firegento\DevDashboard\ViewModel\WidgetArrangement $arrangement */
$arrangement = $block->getData('arrangement');
?>
<div class="flex items-stretch">
    <?php foreach ($arrangement->getChildrenInColumns($block) as $children): ?>
        <div class="devdashboard_developer_widgets w-1/2 pb-56 mx-5">
            <?php foreach ($children as $child): ?>
                <?= $child->toHtml();?>
            <?php endforeach; ?>
        </div>
    <?php endforeach; ?>
</div>

<script type="text/x-magento-init">
        {
            "*": {
                "devDashboard": {}
            }
        }
</script>
