<?php
/** @var Magento\Backend\Block\Template $block */
/** @var \Firegento\DevDashboard\ViewModel\WidgetArrangement $arrangement */
$arrangement = $block->getData('arrangement');
?>
<div class="devdashboard_developer_widgets_wrapper">
    <?php foreach ($arrangement->getChildrenInColumns($block) as $children) : ?>
        <div class="devdashboard_developer_widgets">
            <?php foreach ($children as $child) : ?>
                <?php echo $child->toHtml();?>
            <?php endforeach; ?>
        </div>
    <?php endforeach; ?>
</div>

<script type="text/x-magento-init">
        {
            "*": {
                "devDashboard": {}
            }
        }
</script>