<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Firegento\DevDashboard\ViewModel\Widget\DeployMode $viewModel */
$viewModel = $block->getData('viewModel');
?>
<div class="flex items-center px-5 py-6 shadow-sm rounded-md bg-white">
    <div class="p-3 rounded-full bg-green-400">
        <svg class="h-16 w-16 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h14M5 12a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v4a2 2 0 01-2 2M5 12a2 2 0 00-2 2v4a2 2 0 002 2h14a2 2 0 002-2v-4a2 2 0 00-2-2m-2-4h.01M17 16h.01" />
        </svg>
    </div>
    <div class="mx-5">
        <h4 class="text-2xl font-semibold text-gray-700">
            <?= /** @noEscape */ __('Deploy Mode: %1', $viewModel->getDeployMode());?>
        </h4>
        <div class="text-gray-500"></div>
    </div>
</div>
