<?php
/** @var \Firegento\DevDashboard\ViewModel\Widget\ModuleList $viewModel */
$viewModel = $block->getData('viewModel');
?>
<label for="search_module_list">
    <?= __('Search Module List: ') ?>
</label>
<input id="search_module_list" name="search_module_list" placeholder="<?= __('Search...') ?>" type="text" />

<table class="module_list">
    <thead>
        <tr>
            <th><?= __('Name') ?></th>
            <th>
                <?= __('Type') ?>
                <select class='module_list_filter_type' style='display:inline-block'>
                    <option disabled selected><?= __('Select') ?></option>
                    <option value='core'><?= __('Core') ?></option>
                    <option value='external'><?= __('External') ?></option>
                </select>
            </th>
            <th><?= __('Version') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($viewModel->getModuleList() as $module): ?>
            <tr>
                <td><?= $module['name'] ?>
                <td><?= $module['type'] ?>
                <td><?= $module['setup_version'] ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
