<?php
/** @var Magento\Backend\Block\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Firegento\Devdashboard\ViewModel\Widget\PhpExtensions $viewModel */
$viewModel = $block->getData('viewModel');
?>
<div class="php_extension_widget">
    <h3><?= $escaper->escapeHtml(__('PHP Extensions')) ?></h3>
    <ul>
    <?php foreach ($viewModel->getPhpExtensions() as $extension): ?>
        <?php $phpExtensionStatus = $viewModel->getPhpExtensionStatus($extension); ?>
        <li
            class="<?= $escaper->escapeHtmlAttr($phpExtensionStatus) ?>"
            title="<?= $escaper->escapeHtmlAttr(__($phpExtensionStatus)) ?>">
            <?= $escaper->escapeHtml($extension); ?>
        </li>
    <?php endforeach;  ?>
    </ul>
</div>
