<?php
/** @var Magento\Backend\Block\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Firegento\Devdashboard\ViewModel\Widget\PhpVersion $viewModel */
$viewModel = $block->getData('viewModel');
?>
<div class="flex items-center px-5 py-6 shadow-sm rounded-md bg-white">
    <div class="p-3 rounded-full bg-indigo-600 bg-opacity-75">
<?= file_get_contents(__DIR__ . '/php.svg') ?>
    </div>
    <div class="mx-5">
        <h4 class="text-2xl font-semibold text-gray-700"><?= $escaper->escapeHtml($viewModel->getPhpVersion()) ?></h4>
        <div class="text-gray-500"><?= $escaper->escapeHtml(__('PHP Version')) ?></div>
    </div>
</div>
